services:
  extractor:
    build:
      context: ./knowledge_extractor
      dockerfile: Dockerfile
    volumes:
      - ./knowledge_extractor/app_logs:/app/app_logs
      - ./knowledge_extractor:/app # Mount the app code to the container
      - ./knowledge_extractor/data:/app/data
    env_file:
      - ./knowledge_extractor/.env
    depends_on:
      - qdrant
      - neo4j

  retriever:
    build:
      context: ./retriever
      dockerfile: Dockerfile
    volumes:
      - ./retriever/app_logs:/app/app_logs
      - ./retriever:/app # Mount the app code to the container
    env_file:
      - ./retriever/.env
    ports:
      - 5000:5000
    depends_on:
      - qdrant
      - neo4j

  qdrant:
    image: qdrant/qdrant
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - "./qdrant_storage:/qdrant/storage"

  neo4j:
    image: neo4j:5.17.0
    ports:
      - 7474:7474
      - 7687:7687
    env_file:
      - .env
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
    command: [ "neo4j", "start", "--verbose" ]
