services:
  app:
    build: .
    volumes:
      - ./app_logs:/app/app_logs # Mount logs to the host machine
      - .:/app # Mount the app code to the container
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - qdrant
      - neo4j
    command: sh -c "python main.py"

  qdrant:
    image: qdrant/qdrant
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - "./qdrant_storage:/qdrant/storage"

  neo4j:
    image: neo4j:5.17.0
    ports:
      - 7474:7474
      - 7687:7687
    env_file:
      - .env
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
    command: [ "neo4j", "start", "--verbose" ]
