services:
  app:
    build: .
    env_file: 
      - .env
    ports: 
      - 3000:3000
    depends_on:
      - qdrant
      - neo4j 
    command: sh -c "python main.py"


  
  qdrant:
    image: qdrant/qdrant
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - "$PWD/qdrant_storage:/qdrant/storage:z"
  
  neo4j:
    image: neo4j:5.17.0
    ports:
      - 7474:7474
      - 7687:7687
    env_file: 
      - .env
    volumes:
      - "$PWD/neo4j/data:/data"